version: '3'
services:
  db-bancoa:
    container_name: db-bancoa
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_bancoa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports: 
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-bancob:
    container_name: db-bancob
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_bancob
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports: 
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  db-bancoc:
    container_name: db-bancoc
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_bancoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports: 
      - 5434:5434
    expose:
      - 5434
    command: -p 5434
